# Generated by Django 5.0 on 2023-12-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("address", models.TextField(max_length=255, unique=True)),
                ("role", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contact_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
