# Generated by Django 5.0 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(max_length=255),
        ),
    ]
