# Generated by Django 5.0 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_address_alter_user_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
