# Generated by Django 5.0 on 2023-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
