# Generated by Django 5.0 on 2023-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
